### ISSUE TITLE
Add "Evil Smile" emoji to spritesheet

### ISSUE THREAD

**Issue by kretenkobr2** [BNolet/RLC#102]
1. Put in a **>:D** emoji - [image](http://i.imgur.com/2RY2mmp.png) - narration "with an evil smile"
2. ~~make T_T be equal to ;_;~~
3. ~~Put WTF to be narrated as "WHAT THE FUCK"(wtf can actually pass but what the fuck sounds amazing :D)~~
4. ~~Put btw to be narrated as "By the way"~~
5. ~~Put nvm to be narrated as "Nevermind"(nvm sounds shitty to me)?~~
6. ~~ofc can pass but still could be narrated as "of course"~~

The narration ones are in because WTF and btw sound odd and weird, to me at least, in a TTS... what the fuck and by the way sound way better, even though they are longer

The [Issues are still higher priority though](https://github.com/BNolet/RLC/issues/100)

**Comment by mofosyne** [comment]
Okay here is the snippet for 2 and 3.

```
//Test Input
linetoread = "Testing WTF expansion as well as BTW expansion";

// Abbreviation Expansion (All keys must be in uppercase)
replaceStrList = {"WTF":"What The Fuck", "BTW":"By The Way", "NVM":"Nevermind"};
linetoread = linetoread.split(" ").map(function(token){ 
    if( token.toUpperCase() in replaceStrList ){return replaceStrList[token];}else{return token;};
}).join(" ");

// Test Output 
console.log(linetoread);
```

Outputs:

```
Testing What The Fuck expansion as well as By the way expansion
undefined
```

Using the .map() function for array, which lets you return a new array given a function to iterate over each item in original array.

**Comment by mofosyne** [comment]
abbrev system added now. (left out ofc... tho )

Whats left is the evil emoji

**Comment by mofosyne** [comment]
BTW : By the way
FFS : For Fuck Sake

**Comment by Stjerneklar** [comment]
added T_T and OFC, editing title

**Comment by mofosyne** [comment]
http://www.w3schools.com/jsref/jsref_replace.asp ?

**Comment by Stjerneklar** [comment]
done
