### ISSUE TITLE
User chat activity

### ISSUE THREAD

**Issue by Stjerneklar** [BNolet/RLC#114]
count the number of updates seen from a user in recent user activity

**Comment by BNolet** [comment]
Closing.

**Comment by kretenkobr2** [comment]
Will try looking into this...

**Comment by LewisMCYoutube** [comment]
that sounds like a nice idea

**Comment by mofosyne** [comment]
Every 10 mins, post and remove a "ping" message so inactive users can be tracked

**Comment by LewisMCYoutube** [comment]
Every 1 min, remove and post a "pong" message so active users can be tracked

**Comment by Stjerneklar** [comment]
3.22 adds this feature.
adding an issue for the proposed idea of actively tracking inactivity :)
