### ISSUE TITLE
Feature: Load live room messages | Experimentally implemented

### ISSUE THREAD

**Issue by Stjerneklar** [BNolet/RLC#12]
we currently cannot access the default history since it is loaded by scrolling the body.
this behavior combined with our chatwindow being fixed height meant that messages were either no loaded or loaded too far back slowing everything to a crawl.

a controlled way to load history would be very nice.

one way would be to have a button that causes new css classes to be applied that size the body to be scrollable, and then scrolls it before removing the classes and making scrolling impossible again.

another would be to find the current mechanism for scrolling and calling the function that it calls. tried looking at event handlers but no luck.

**Comment by dashed** [comment]
https://davidwalsh.name/detect-node-insertion

**Comment by Stjerneklar** [comment]
Added an option to cause the body element to be scrollable. this loads old messages that are properly handled.

**Comment by Stjerneklar** [comment]
as of RLC v.2.17 a "load messages" button has been added above sidebar option toggles that triggers reddit lives native message load.
