### ISSUE TITLE
Version 2.30.3 of script malfunctioning on Mac

### ISSUE THREAD

**Issue by teamvista** [BNolet/RLC#120]
Using:
- Chrome 50.0.2661.86
- Mac OSX 10.10.5

![screen shot 2016-04-30 at 12 15 06](https://cloud.githubusercontent.com/assets/5490551/14937257/0033f11e-0ed0-11e6-8b4c-1a4b1e96f49e.png)

**Comment by Stjerneklar** [comment]
anyone got an idea of how to debug this?

also, did you find out what version broke rlc for you?

**Comment by teamvista** [comment]
v.2.29.32 started breaking things, didn't bother with any versions after that

**Comment by teamvista** [comment]
Working now with 2.30.5, closing this.
