### ISSUE TITLE
Cannot load old messages [Firefox]

### ISSUE THREAD

**Issue by mofosyne** [BNolet/RLC#133]

**Comment by Stjerneklar** [comment]
is this still occuring?

**Comment by mofosyne** [comment]
Still an ongoing issue. Try loading message in chrome

**Comment by BNolet** [comment]
Issue only occurs in Firefox. Using ver. 46

**Comment by Stjerneklar** [comment]
issue was also spotted in chrome but fixed, closing

**Comment by Stjerneklar** [comment]
fixed after transition to new message retrival system via api.
