### ISSUE TITLE
Concept: Mimic Robin

### ISSUE THREAD

**Issue by Stjerneklar** [BNolet/RLC#134]
idea was brought up in the topic of how to attract users, and it occured to us that we could make RLC look exactly like robin initialy, with options to transform it into what it is now.

this would let users gradually get into the experience instead of being spooked by all the features and the alien look.

Robin CSS(actually LESS):
https://github.com/reddit/reddit-plugin-robin/blob/8ec7f516407d262862b2da08d083257271f31f83/reddit_robin/public/static/css/robin.less

**Comment by mofosyne** [comment]
For anyone who wants to test his fork:
- https://github.com/Stjerneklar/RLC/raw/master/rlcs.user.js

**Comment by Stjerneklar** [comment]
this has been done to the extent that i envisioned as of 3.6 , further improvement can be tracked in specific issues.
