### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by Stjerneklar** [BNolet/RLC#2]
Okay so it kinda works like a chat now but it dosen't look like it.

im thinking of styling this pretty much like robin, will take a swing at it later.

for now i've made the usernames appear in the left(or below since im just float:left-ing it)

**Comment by bales75** [comment]
FYI this is what it looks like currently with 4:3 aspect ratio 1720x1440 http://i.imgur.com/l6q7lDz.png

**Comment by Stjerneklar** [comment]
closed, way out of date
