### ISSUE TITLE
option to clear/crop chat after a certain number of messages

### ISSUE THREAD

**Issue by Stjerneklar** [BNolet/RLC#200]

**Comment by ConcernedHobbit** [comment]
Suggestion: Option to keep removing old messages to keep message number at x (maybe hiding so they can be loaded later)

**Comment by BNolet** [comment]
Suggestion:
1. Default = auto-discard old messages after x amount (ideal would be 50)
2. Option: x amount is modifiable in options
3. Option: Keep all messages

**Comment by Stjerneklar** [comment]
ive done this in my fork, pending merge

**Comment by Stjerneklar** [comment]
merged to testing, closing and adding req for option 2
