### ISSUE TITLE
Idea: Show more precise times on posted messages

### ISSUE THREAD

**Issue by ConcernedHobbit** [BNolet/RLC#22]
Due to the way the live system works, everything newer than a minute is "just now". Instead, how about changing it to [seconds] ago?

**Comment by Stjerneklar** [comment]
I think it might get a bit annoying if the time tag tracked seconds, since this would cause constant updating when below a minute.

**Comment by ConcernedHobbit** [comment]
Every five seconds then? Or just a timestamp would suffice, I guess.

**Comment by Stjerneklar** [comment]
timestamps have been implemented

**Comment by ConcernedHobbit** [comment]
To closer: Reference commit that added functionality. (75c6321)
