### ISSUE TITLE
Add LICENCE file

### ISSUE THREAD

**Issue by LewisMCYoutube** [BNolet/RLC#228]

**Comment by LewisMCYoutube** [comment]
i suggest copyrighting it

**Comment by dashed** [comment]
I vote MIT.

**Comment by kretenkobr2** [comment]
Here is survey for anyone interested: https://docs.google.com/forms/d/1C1KLR0Eq6refTRqZ5ZmpIuLckv0BiFprFElxlkYQFXM/viewform
