### ISSUE TITLE
Twitch emotes

### ISSUE THREAD

**Issue by dashed** [BNolet/RLC#23]

**Comment by dashed** [comment]
After around April 24, I might PR this if it isn't implemented yet.

**Comment by Stjerneklar** [comment]
XD

**Comment by mobiuscoffee** [comment]
Paging @dashed

**Comment by dashed** [comment]
kappa kappa kappa

**Comment by kretenkobr2** [comment]
List here Twitchmotes you want...

**Comment by Stjerneklar** [comment]
this is now in 3.15.8 made by kreten :D

**Comment by dashed** [comment]
Good job! 👍
