### ISSUE TITLE
Feature: User activity list

### ISSUE THREAD

**Issue by dashed** [BNolet/RLC#25]
There doesn't seem to be a trivial way to know who is currently in the live thread.

As a compromise, might be useful to maintain a list of active users who have sent a message in the past N minutes.

**Comment by Stjerneklar** [comment]
Great idea

**Comment by touya-akira** [comment]
We talked about another idea today: Since we have reddit.today and GuitarShirt maintaining the servers behind it, we could have the script send userinfo to the website (pretty much like parrot and other robin-scripts sent channel info back to robintracker). From which the script can generate an accurate user list.

Possibly make that opt-in.

**Comment by dashed** [comment]
Unsure about 3rd-party tracking =/. Tracking list of users who have sent a message in last 10 minutes seems like a simpler solution.

---

By extension, you could have RLC announce user entering chat in `:announce` channel. The same channel could be used to announce that users are afk, away, online, etc.

You could even have RLC send 'pings'  to  `:announce` channel every 5 minutes to keep the user activity lists of every other user fresh.

Essentially you would treat the chat as a glorified message bus.

**Comment by touya-akira** [comment]
That's perfectly fine. You guys just need to coordinate how to implement it best, was just initiating the idea since the raw data from reddit isn't really useful.

**Comment by mofosyne** [comment]
Btw, use this list to make autocomplete more context sensitive to recent user activity

**Comment by mofosyne** [comment]
Isn't this finished?

**Comment by kretenkobr2** [comment]
This should be finished right?

**Comment by Stjerneklar** [comment]
yeah true, kept it because of the discussion, but lets close this since the feature itself is in
