### ISSUE TITLE
Option to not display seconds in timestamps

### ISSUE THREAD

**Issue by UnderTheHole** [BNolet/RLC#255]
Currently on RLC v3.16.2, which is the branch testing. 

I don't know if it occurs by region, but I have the "bug" and couple of others too. However, Stjernklar doesn't have it which I think is because he's using 24 hour time. 

I have 12 hour time. I use PST, if that helps. 

Here's a screenshot: http://puu.sh/oROfy/944d737050.png

**Comment by Stjerneklar** [comment]
i must be using the wrong date function in the timeandusertracking section, will revise.

**Comment by Stjerneklar** [comment]
fix attempted in 3.16.6, merged to testing branch

**Comment by Stjerneklar** [comment]
times should now be in 24 hour. guess i can add option to show times as 12 hour...

**Comment by kretenkobr2** [comment]
this is not a bug, why shouldn't they show sec's?

**Comment by dashed** [comment]
Compromise by having option to hide the seconds.
