### ISSUE TITLE
[Firefox] Voice pitch change causes TTS to stop working

### ISSUE THREAD

**Issue by kretenkobr2** [BNolet/RLC#293]
Can be "bypassed" by not using float numbers for pitch because:

> SAPI's absmiddle attibute doesn't allow float type. Example, when pitch was 0.75, abmiddle was -2.5. So ISpVoice.Speak() will return error.

Numbers with single decimal place DO work (i.e. 1.4, 1.5, 1.3) while numbers with two decimal places(0.75, 1.45 etc) don't work...

**Comment by ConcernedHobbit** [comment]
Fixed by #294
