### ISSUE TITLE
No Deletion Option/Deleted message still readable

### ISSUE THREAD

**Issue by Stjerneklar** [BNolet/RLC#299]
might be a feature in demand at some point or in a more new ticker oriented usage

**Comment by Stjerneklar** [comment]
with our seperate message system, should be as simple as not processing websocket delete calls.
ofc, these messages will not persist trough reload

**Comment by ConcernedHobbit** [comment]
I disagree. Discord and most new chat apps have the ability to edit and remove messages you have sent. Maybe replace them with [removed] instead until reload?
