### ISSUE TITLE
Automatic Channel Discovery

### ISSUE THREAD

**Issue by mofosyne** [BNolet/RLC#30]
The https://github.com/5a1t/parrot project includes an automatic channel discovery feature. It monitors all the first word of each message if its of a form that indicates "channel", and then ranks it in a list so people can choose to add or remove channels.

Alternatively you could just make the tab automatically adapt to whatever channels exist at a given period.

**Comment by mofosyne** [comment]
https://github.com/5a1t/parrot/issues/134 this is the issue for the completed feature of auto channel discovery

**Comment by Stjerneklar** [comment]
Automatic Channel Discovery was removed for lack of interest in making it work. the code is in the history somewhere if we want to revisit it.

**Comment by ConcernedHobbit** [comment]
Closing for now. See above comment.
