### ISSUE TITLE
[URGENT] Make an option to read long messages(those which are expandable and contractable with + or - sign)

### ISSUE THREAD

**Issue by kretenkobr2** [BNolet/RLC#302]
We need an option to read expandable messages(too long ones) for live threads, such as the current one: https://www.reddit.com/live/wy0st0j6out0

**Comment by mofosyne** [comment]
```
        // long messages break tts (<300 chars)
        if($msg.text().length<250){
```

**Comment by kretenkobr2** [comment]
this is up since 3.18.9

**Comment by ConcernedHobbit** [comment]
For future notice, please use tags instead of brackets in the title. Makes sorting easier.

**Comment by kretenkobr2** [comment]
how to put tag?
