### ISSUE TITLE
the chatbox is white so i can't see what i'm typing

### ISSUE THREAD

**Issue by 0Hyp3r10n0** [BNolet/RLC#306]
here's an image: http://imgur.com/SLw33R4
I'm on v3.18.10
pls halp

**Comment by LewisMCYoutube** [comment]
is the text black?

**Comment by 0Hyp3r10n0** [comment]
nope

**Comment by 0Hyp3r10n0** [comment]
it's completely white, you can't see it while typing

**Comment by LewisMCYoutube** [comment]
oh

**Comment by 0Hyp3r10n0** [comment]
it works now yayyyyyyyyyyyyyyyyyyyy
 https://github.com/Stjerneklar/RLC/raw/testing/rlcs.user.js

**Comment by LewisMCYoutube** [comment]
yayyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

**Comment by Stjerneklar** [comment]
merging in the fix
