### ISSUE TITLE
Some users have complained about the name.

### ISSUE THREAD

**Issue by Stjerneklar** [BNolet/RLC#33]
Please note your alternative suggestions in this issue.

Current suggestions:

RLC: Reddit Live Chat
(very descriptive, nice and short, already the name of the .js file)

LiveBird
(reddit live + bird reference game on point)

FreeBird
(funny namee + bird reference game on point 

Phoenix
(rebirth of robin/parrot + bird reference game on point)

Chatter

A CHALLENGER APPEARS:  RECT - Reddit Enhanced Chat Terminal
can be backronymed, but RECT could be both accurate and well memed

suggested by dashed, met with much appreciation in the chat at the time from both proponents and detractors of FukBird

**Comment by rramos-code** [comment]
I think the current name will work for now.
i mean, it makes since. But i get the possible need to replace it.

**Comment by bales75** [comment]
FBird

**Comment by FlamingObsidian** [comment]
I guess for now it will be kinda like Brainfuck.

**Comment by Stjerneklar** [comment]
RLC with the come from behind win!
