### ISSUE TITLE
Minor color alternation glitch until next message

### ISSUE THREAD

**Issue by FlamingObsidian** [BNolet/RLC#43]
The colors did not alternate between light and dark. I think this may have something to do with long usernames.

**Comment by MrSpicyWeiner** [comment]
I'm not really seeing what you mean.. Can you give any more info?

**Comment by Stjerneklar** [comment]
ive seen this bug happen but i have not been able to recreate it.

in the case i observed, the alt-bg class was simply applied on two elements in a row, wich should be impossible unless content is disapearing.

**Comment by MrSpicyWeiner** [comment]
Entirely possible since you can delete messages. Sounds like you're doing a funky way of coloring the background. I'm at work and unable to check right now

**Comment by Stjerneklar** [comment]
closed and replaced with a more up to date summary of the issue here: https://github.com/BNolet/RLC/issues/115
