### ISSUE TITLE
autocomplete multiple match tab cycling

### ISSUE THREAD

**Issue by touya-akira** [BNolet/RLC#49]
currently nick completion only works for the first word you type. It should be possible anywhere in the line.

Also, If the completion search only finds one exact match, it should spell out the nick and add a whitespace behind it - so you don't need to tab again and can just continue typing the next word.

if multiple matches are found tab will cycle through the rest of the possible names _without_ adding a space.

**Comment by mofosyne** [comment]
Also make sure that autocomplete searches by most recent username activity first, before looking up the rest of the userlist.

**Comment by MrSpicyWeiner** [comment]
Alright I have the basics of this out. There's no tab cycling though.

**Comment by Stjerneklar** [comment]
not going to persue this, current solution is nice and elegant
