### ISSUE TITLE
Embeds

### ISSUE THREAD

**Issue by rramos-code** [BNolet/RLC#7]
Embeds look way too jarring. I think the add on should somehow find a way to disable these and just put a link.

**Comment by Stjerneklar** [comment]
agreed, possibly find a way to let them be viewable on page but initially collapse to link.
kinda hard atm since the build in code renders the embeds directly into iframes that can only really be identified as iframes. ill look at solutions.

**Comment by rramos-code** [comment]
cool. Thanks!

**Comment by Stjerneklar** [comment]
had an idea on how to bypass embedly, the buildt in process for embeds: 
parse outgoing and incoming messages to "encrypt" them to prevent recognition as a link during the time where reddit is handling the message. eg: 

aaaa://bbb.youtube.com/watch?v=ih0SaC_rrbA

where we replace http with 4 a's and www with 3 b's.
major con with this is that we make content unavailible to non users of script.

**Comment by Stjerneklar** [comment]
i figured out that links are not embedded if they are posted in a message that also contains any text.
if there is text, the link is displayed as a link instead of being embedded.

therefore, all messages are now sent with a trailing space, preventing embeds but allowing links.
