### ISSUE TITLE
Minor inconsistencies after refresh

### ISSUE THREAD

**Issue by touya-akira** [BNolet/RLC#75]
_Note: Maybe tag this as "Known Issue" or even present in the readme somewhere._

Whenever refreshing the browser tab, a few oddities may happen: The background for chat lines may repeat once and Chrome notifications might be confused. This is normal behavior and not a bug (unless we find more serious effects).

**Comment by Stjerneklar** [comment]
notifications should be fixed, chatline problem is documented in seperate issue
