### ISSUE TITLE
Activate RLC only upon detection of a trigger word

### ISSUE THREAD

**Issue by mofosyne** [BNolet/RLC#76]
To not override every other reddit live channels (potentially annoying users), make it such that you need to add a special key word in the sidebar to activate this userscript.

E.g.

If you insert this to sidebar:

`[Activate Reddit Live Chat](https://github.com/BNolet/RLC/raw/master/rlcs.user.js)`

it would activate the userscript because it detected the keywords "Activate Reddit Live Chat" in a link description.

**Comment by Stjerneklar** [comment]
I'm not sure that the potential annoyance of incompetent users (those who cannot disable a userscript if they want to) should rank higher than the capacity for RLC to be used anywhere without aproval from the room owners.

I would rather give people an option to opt out of RLC usage on a room basis via a setting, than require rooms to allow RLC.

open to arguments but the one you have stated here feels too minor.

**Comment by MrSpicyWeiner** [comment]
I agree with Stjerneklar. If someone doesn't want to use it on a page they can turn it off for that page
