### ISSUE TITLE
Using Reddit.today domain to help people install

### ISSUE THREAD

**Issue by Stjerneklar** [BNolet/RLC#79]
Link to RLC with reddit.today/chat.

add reddit.today/chat to the list of sites for RLC extension to run.
add a check to RLC that runs when on reddit.today/chat only, that redirects to the chat as normaly.
remove reddit.today/chat redirection to the chat room, and instead place install info on reddit.today/chat.

**Comment by kretenkobr2** [comment]
Close this, reddit.today reddirects to github and install info while reddit.today/chat reddirects to chat

**Comment by Stjerneklar** [comment]
oh yeah, guess we should note that somewhere. putting it in readme
