### ISSUE TITLE
Text To Speech API

### ISSUE THREAD

**Issue by mofosyne** [BNolet/RLC#83]
If you guys are interested, it may be a fun experiment if you could have text to speech that assign a different voice to each nick.

https://developers.google.com/web/updates/2014/01/Web-apps-that-talk-Introduction-to-the-Speech-Synthesis-API

---

An example of this concept in action is http://briankhuu.com/shoutbox/shoutbox_TTS.html

---

Client side synth via js: http://www.masswerk.at/mespeak/

**Comment by Stjerneklar** [comment]
that **is** interesting...

implemented in v.2.22

**Comment by mofosyne** [comment]
Next things to add:
- Multiple voice for each nick
- Intonation for sarcasm `\s`
- Speed modifier `\slow`
- Nick announce if not using different voices.
