### ISSUE TITLE
Detect repeated messages to prevent narration if same person speaks twice.(TTS)

### ISSUE THREAD

**Issue by Stjerneklar** [BNolet/RLC#85]
user specific voices ala user colors.

choose narration style: before message, after message, user specific voice(no narration)

detect repeated messages to prevent narration if same person speaks twice.

**Comment by mofosyne** [comment]
Also added a pull request to make narration style based on last character, if its a question, exclamation or sarcasm.

**Comment by mofosyne** [comment]
Here is the cheapish psudorandomisation function I will use to select a random integer based on a username string. Feel free to use it for anything else. 

```
// Cheap String Seeded Psudo Random Int Hash (Author: mofosyne)
function strSeededRandInt (str,min=0,max=256,code=0){ 
    for(i=0;i<str.length;i++){
        code += str.charCodeAt(i);
    }
    return code%(1+max-min)+min;
}
```

Do not rely on this to protect critical code... its very similar to CRC, so collision is easy for this.

**Comment by mofosyne** [comment]
This this important anymore, now that username tts is optional? Probbly just close this.
